DROP TABLE Player CASCADE CONSTRAINTS;
DROP TABLE PlayerRunScore CASCADE CONSTRAINTS;
DROP TABLE ChessGame CASCADE CONSTRAINTS;
DROP TABLE Run CASCADE CONSTRAINTS;


CREATE TABLE Player (
	id NUMBER(4) PRIMARY KEY,
	name VARCHAR2(40) NOT NULL,
	chess_ilo NUMBER(4)
);

CREATE TABLE PlayerRunScore (
	id NUMBER(4) PRIMARY KEY,
	overall NUMBER(4) NOT NULL,
	first NUMBER(4) NOT NULL,
	second NUMBER(4) NOT NULL,
	third NUMBER(4) NOT NULL,
	forth NUMBER(4) NOT NULL,
	player_id NUMBER(4) NOT NULL UNIQUE REFERENCES Player
);

CREATE TABLE ChessGame (
	id NUMBER(4) PRIMARY KEY,
	white_id NUMBER(4) NOT NULL REFERENCES Player,
	black_id NUMBER(4) NOT NULL REFERENCES Player,
	result NUMBER(4) NOT NULL
);

CREATE TABLE Run (
	id NUMBER(4) PRIMARY KEY,
	first_id NUMBER(4) NOT NULL REFERENCES Player,
	second_id NUMBER(4) NOT NULL REFERENCES Player,
	third_id NUMBER(4) NOT NULL REFERENCES Player,
	forth_id NUMBER(4) NOT NULL REFERENCES Player
);
